org: kleach12
app: first-step-function
service: first-step-function
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  firstStepFunction:
    handler: firstStepFunction.handler

stepFunctions:
  stateMachines:
    helloStepFunction:
      name: helloStepFunction
      events:
        - httpApi:
            path: /first-step
            method: get
      definition:
        Comment: "A Hello World example of the Amazon States Language using a Pass state"
        StartAt: FirstStepFunction
        States:
          FirstStepFunction:
            Type: Task
            Result: "Hello World!"
            End: true

plugins:
  - serverless-step-functions
