org: kleach12
app: first-step-function
service: first-step-function
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  processPurchase:
    handler: processPurchase.handler
  processRefund:
    handler: processRefund.handler

stepFunctions:
  stateMachines:
    ProcessPaymentStepFunction:
      name: ProcessPaymentStepFunction
      events:
        - httpApi:
            path: /first-step
            method: get
      definition:
        Comment: "A Hello World example of the Amazon States Language using a Pass state"
        StartAt: ProcessTransaction
        States:
          ProcessTransaction:
            Type: Choice
            Choices: [
              {
                Variable: "$.TransactionType",
                StringEquals: "PURCHASE",
                Next: "ProcessPurchase"
              },
              {
                Variable: "$.TransactionType",
                StringEquals: "REFUND",
                Next: "ProcessRefund"
              }
            ]
          ProcessPurchase:
            Type: Task
            Resource:
              Fn::GetAtt: [processPurchase, Arn]
            End: true
          ProcessRefund:
            Type: Task
            Resource:
              Fn::GetAtt: [processRefund, Arn]
            End: true

plugins:
  - serverless-step-functions
